### ISSUE TITLE
Chat controls phase in/out when browser is maximized 

### ISSUE THREAD

**Issue by kwallace0906** [xHergz/TheMakeupApp#127]
### Description:
When browser maximized, the chat controls (mic/camera/full screen toggle/back button) phase in and out with the mouse controls but when in a smaller sized browser they are where they are supposed to be. 
### Reproduction Steps:
Enter an active call and maximize the browser. 
### Proposed Solution:
Tweak control styling for full screen browser settings.

**Comment by xHergz** [comment]
Fixed in latest version of development branch.
